{
 "title": "Ambev Dashboard",
 "tags": [ "Ambev" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "HealthChecks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Liveness",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ambev_healthcheck_status{name=\"Liveness\"}"
    }
   ]
  },
  {
   "title": "Readiness",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ambev_healthcheck_status{name=\"Readiness\"}"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ambev_healthcheck_status{name=\"postgres\"}"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ambev_healthcheck_status{name=\"redis\"}"
    }
   ]
  },
  {
   "title": "RabbitMQ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ambev_healthcheck_status{name=\"rabbitmq\"}"
    }
   ]
  },
  {
   "title": "Seq",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ambev_healthcheck_status{name=\"seq\"}"
    }
   ]
  },
  { "title": "RabbitMQ Queues (Real Time)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "q.sale.created",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"q.sale.created\"}"
    }
   ]
  },
  {
   "title": "q.sale.updated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"q.sale.updated\"}"
    }
   ]
  },
  {
   "title": "q.sale.cancelled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"q.sale.cancelled\"}"
    }
   ]
  },
  { "title": "RabbitMQ Queues (Processed)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "q.sale.created (total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_delivered_total{queue=\"q.sale.created\"}"
    }
   ]
  },
  {
   "title": "q.sale.updated (total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_delivered_total{queue=\"q.sale.updated\"}"
    }
   ]
  },
  {
   "title": "q.sale.cancelled (total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_delivered_total{queue=\"q.sale.cancelled\"}"
    }
   ]
  },
  { "title": "Tables Count Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Sales",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS value FROM \"Sales\";"
    }
   ]
  },
  {
   "title": "SaleItems",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS value FROM \"SaleItems\";"
    }
   ]
  },
  {
   "title": "Products",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS value FROM \"Products\";"
    }
   ]
  },
  {
   "title": "Branches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS value FROM \"Branches\";"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS value FROM \"Users\";"
    }
   ]
  }
 ]
}