apiVersion: 1

datasources:
  - name: grafana-postgresql-datasource
    type: grafana-postgresql-datasource
    access: proxy
    uid: afb90jh5334e8c
    url: ambev.developerevaluation.database:5432
    database: developer_evaluation
    user: developer
    secureJsonData:
      password: ev@luAt10n
    jsonData:
      sslmode: disable
      postgresVersion: 1300
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      database: developer_evaluation
    version: 1
    editable: false
