apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://ambev.developerevaluation.prometheus:9090
    isDefault: true
    version: 1
    editable: false
